//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLibri
    {
        public int id { get; set; }
        public string Nome { get; set; }
        public string Seriale { get; set; }
        public Nullable<decimal> Prezzo { get; set; }
        public int idUtente { get; set; }
    
        public virtual BookUtenti BookUtenti { get; set; }
    }
}
