//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoinGuadagnate
    {
        public int id { get; set; }
        public string Descrizione { get; set; }
        public int Quantità { get; set; }
        public int idUtente { get; set; }
        public System.DateTime Attivazione { get; set; }
    
        public virtual Utenti Utenti { internal get; set; }
    }
}
