//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.CouponAttivi = new HashSet<CouponAttivi>();
        }
    
        public int Codice { get; set; }
        public Nullable<decimal> xAttivazione { get; set; }
        public Nullable<decimal> yAttivazione { get; set; }
        public Nullable<decimal> Raggio { get; set; }
        public int idCreatore { get; set; }
        public int Valore { get; set; }
        public System.DateTime Creazione { get; set; }
        public string Nome { get; set; }
        public bool Attivo { get; set; }
    
        public virtual Utenti Utenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponAttivi> CouponAttivi { internal get; set; }
    }
}
