//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseString : DbContext
    {
        public DatabaseString()
            : base("name=DatabaseString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ads> Ads { get; set; }
        public virtual DbSet<Analytics> Analytics { get; set; }
        public virtual DbSet<Avvisi> Avvisi { get; set; }
        public virtual DbSet<BookLibri> BookLibri { get; set; }
        public virtual DbSet<BookUtenti> BookUtenti { get; set; }
        public virtual DbSet<OggettiSondaggi> OggettiSondaggi { get; set; }
        public virtual DbSet<SalveminiCard> SalveminiCard { get; set; }
        public virtual DbSet<Sondaggi> Sondaggi { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<VotiSondaggi> VotiSondaggi { get; set; }
        public virtual DbSet<EventsLog> EventsLog { get; set; }
        public virtual DbSet<AppInfo> AppInfo { get; set; }
        public virtual DbSet<Giornalino> Giornalino { get; set; }
        public virtual DbSet<Materie> Materie { get; set; }
    }
}
