//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sondaggi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sondaggi()
        {
            this.OggettiSondaggi = new HashSet<OggettiSondaggi>();
            this.VotiSondaggi = new HashSet<VotiSondaggi>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public int Creatore { get; set; }
        public System.DateTime Creazione { get; set; }
        public bool Attivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OggettiSondaggi> OggettiSondaggi { get; set; }
        public virtual Utenti Utenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotiSondaggi> VotiSondaggi { internal get; set; }
    }
}
