//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalveminiApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utenti()
        {
            this.Avvisi = new HashSet<Avvisi>();
            this.Sondaggi = new HashSet<Sondaggi>();
            this.VotiSondaggi = new HashSet<VotiSondaggi>();
            this.Coupon = new HashSet<Coupon>();
            this.CouponAttivi = new HashSet<CouponAttivi>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Sesso { get; set; }
        public int Classe { get; set; }
        public string Corso { get; set; }
        public int Stato { get; set; }
        public System.DateTime Creazione { get; set; }
        public string ArgoToken { get; set; }
        public int sCoin { get; set; }
        public int AdsWatched { internal get; set; }
        public Nullable<System.DateTime> LastAdWatched { internal get; set; }
        public System.DateTime Compleanno { get; set; }
        public string Residenza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avvisi> Avvisi { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sondaggi> Sondaggi { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotiSondaggi> VotiSondaggi { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupon { internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponAttivi> CouponAttivi { internal get; set; }
    }
}
